### ISSUE TITLE
name 'out_pred' is not defined

### ISSUE THREAD

**Issue by rachel-sorek** [NVAITC/bert-finetune#3]
Im trying to run bert_layer.ipynb and on block, and line: 
`model = tf.keras.models.Model(inputs=in_bert, outputs=out_pred)`

return this error:

> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> <ipython-input-15-351668d1d10f> in <module>
> ----> 1 model = tf.keras.models.Model(inputs=in_bert, outputs=out_pred)
> 
> NameError: name 'out_pred' is not defined

**Comment by tlkh** [comment]
Hi, sorry I was messing around with the notebook and accidentally committed some draft changes. Looking at the current notebook, if you replace `out_pred` with `x` it should work.

Apologies as I wasn't expecting someone to discover this repository so early. I'm still making changes.

**Comment by rachel-sorek** [comment]
Thanks, that solved it!
